// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/horonlee/ginhub/internal/config"
	"github.com/horonlee/ginhub/internal/data"
	"github.com/horonlee/ginhub/internal/handler"
	"github.com/horonlee/ginhub/internal/server"
	"github.com/horonlee/ginhub/internal/service"
)

// Injectors from wire.go:

// InitServer 初始化服务器（Wire自动生成依赖注入代码）
func InitServer(cfg *config.AppConfig) (*server.HTTPServer, error) {
	db, err := data.NewDB(cfg)
	if err != nil {
		return nil, err
	}
	helloWorldRepo := data.NewHelloWorldRepo(db)
	helloWorldService := service.NewHelloWorldService(helloWorldRepo)
	helloWorldHandler := handler.NewHelloWorldHandler(helloWorldService)
	httpServer := server.NewHTTPServer(cfg, helloWorldHandler, db)
	return httpServer, nil
}
