// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/HoronLee/GinHub/internal/config"
	"github.com/HoronLee/GinHub/internal/data"
	"github.com/HoronLee/GinHub/internal/handler"
	"github.com/HoronLee/GinHub/internal/server"
	"github.com/HoronLee/GinHub/internal/service"
	"github.com/HoronLee/GinHub/internal/util/log"
)

// Injectors from wire.go:

// InitServer 初始化服务器
func InitServer(cfg *config.AppConfig) (*server.HTTPServer, error) {
	logger := util.NewLogger(cfg)
	db, err := data.NewDB(cfg, logger)
	if err != nil {
		return nil, err
	}
	helloWorldRepo := data.NewHelloWorldRepo(db)
	helloWorldService := service.NewHelloWorldService(helloWorldRepo)
	helloWorldHandler := handler.NewHelloWorldHandler(helloWorldService)
	handlers := handler.NewHandlers(helloWorldHandler)
	httpServer := server.NewHTTPServer(cfg, handlers, db, logger)
	return httpServer, nil
}
